name: Generate GitHub Snake

on:
  schedule:
    # Run once every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # You need to fetch all history for git actions
          fetch-depth: 0

      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: arunchapagain
          # Generate the contribution graph as an SVG
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - uses: crazy-max/ghaction-github-pages@v4
        with:
          # The source directory for the generated files
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}